# Generated by Django 6.0.7 on 2026-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_alter_userinfo_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='ussername',
            new_name='username',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.CharField(blank=True, choices=[('Job Seeker', 'Job Seeker'), ('Employer', 'Employer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
